services:
  express-api:
    build:
      context: ./express-api
      dockerfile: Dockerfile
    container_name: express_api
    depends_on:
      - redis
      - laravel-app
    ports:
      - "3001:3001"
    volumes:
      - ./express-api/src:/app
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LARAVEL_API_URL=http://laravel-app:8000/api/v1
      - CACHE_TTL=300
    command: sh -c "npm install && npm run dev"
    stdin_open: true
    tty: true
    networks:
      - backend
      - cache

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    stdin_open: true
    tty: true

  laravel-app:
    build:
      context: ./laravel-app
      dockerfile: Dockerfile
    container_name: laravel_app
    depends_on:
      - laravel-db
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./laravel-app/src:/var/www/html
    environment:
      DB_HOST: laravel-db
      DB_DATABASE: laravel
      DB_USERNAME: admin
      DB_PASSWORD: qwertyui
      APP_URL: http://localhost:8000
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: sh -c "composer install && php artisan migrate && php artisan serve --host=0.0.0.0 --port=8000"
    networks:
      - db
      - backend
      - cache

  laravel-db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: admin
      MYSQL_PASSWORD: qwertyui
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: laravel-db
      PMA_PORT: 3306
      PMA_USER: admin
      PMA_PASSWORD: qwertyui
      UPLOAD_LIMIT: 300M
    networks:
      - db
    depends_on:
      - laravel-db

  redis:
    image: redis:7.0.4
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - cache
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:

networks:
  cache:
    driver: bridge
  db:
    driver: bridge
  backend:
    driver: bridge